# Generated by Django 3.1.2 on 2020-11-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'personal', 'verbose_name_plural': 'personal'},
        ),
    ]
