# Generated by Django 3.1.2 on 2020-11-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_auto_20201115_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('SIN CARGO ASIGNADO', 'SIN CARGO ASIGNADO'), ('SECRETARIA', 'SECRETARIA'), ('PROFESIONAL MEDICO', 'PROFESIONAL MEDICO'), ('VENTAS', 'VENTAS'), ('TALLER', 'TALLER'), ('GERENCIA', 'GERENCIA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
