# Generated by Django 3.1.2 on 2020-11-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funciones', '0004_auto_20201117_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentasFinalizas',
        ),
    ]
