# Generated by Django 3.1.2 on 2020-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funciones', '0005_delete_ventasfinalizas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='producto',
            field=models.CharField(max_length=250),
        ),
    ]
